export type SupportedPlatform =
  | 'youtube'
  | 'instagram'
  | 'tiktok'
  | 'twitter'
  | 'facebook'
  | 'generic_media'
  | 'direct_file';

export type MediaType = 'video' | 'audio' | 'playlist' | 'direct';

export type StandardQuality = '2160p' | '1440p' | '1080p' | '720p' | '480p' | '360p' | 'audio_only';

export type TargetContainer = 'mp4' | 'mkv' | 'webm' | 'mp3' | 'm4a' | 'flac';

export type MediaDownloadStage =
  | 'extracting'
  | 'downloading_video'
  | 'downloading_audio'
  | 'downloading_stream'
  | 'merging_streams'
  | 'converting_audio'
  | 'verifying'
  | 'retrying'
  | 'completed'
  | 'error'
  | 'cancelled';

export interface MediaFormatOption {
  formatId: string;
  ext: string;
  resolution?: string;
  width?: number;
  height?: number;
  fps?: number;
  vcodec?: string;
  acodec?: string;
  filesize?: number;
  filesizeApprox?: number;
  tbr?: number; // Total bitrate (kbps)
  vbr?: number; // Video bitrate (kbps)
  abr?: number; // Audio bitrate (kbps)
  qualityLabel?: string; // e.g. "1080p60", "720p", "320kbps"
  formatNote?: string;
  isPremium?: boolean;
  hasDrm?: boolean;
  hasVideo: boolean;
  hasAudio: boolean;
  isDashStream: boolean; // Needs separate audio stream
  url?: string;
  protocol?: string;
  httpHeaders?: Record<string, string>;
}

export interface MediaSubtitleOption {
  lang: string;
  name: string;
  ext: string;
  url: string;
  isAutoGenerated: boolean;
}

export interface MediaChapter {
  title: string;
  startTime: number;
  endTime: number;
}

export interface PlaylistItemInfo {
  id: string;
  title: string;
  url: string;
  duration?: number;
  thumbnail?: string;
  uploader?: string;
}

export interface MediaInfo {
  id: string;
  originalUrl: string;
  platform: SupportedPlatform;
  mediaType: MediaType;
  title: string;
  cleanFileName: string;
  description?: string;
  uploader?: string;
  uploaderUrl?: string;
  duration?: number; // In seconds
  formattedDuration?: string;
  thumbnail?: string;
  availableFormats: MediaFormatOption[];
  subtitles?: MediaSubtitleOption[];
  chapters?: MediaChapter[];
  playlist?: {
    id: string;
    title: string;
    itemCount: number;
    items: PlaylistItemInfo[];
  };
  extractorName: string;
  extractedAt: number;
  rawMetadata?: Record<string, any>;
}

export interface MediaDetectionResult {
  isMediaUrl: boolean;
  platform: SupportedPlatform;
  canonicalUrl: string;
  mediaTypeHint: MediaType;
  videoIdOrId?: string;
}

export interface ExtractionOptions {
  cookiesPath?: string;
  browserCookies?: string; // e.g. "chrome", "edge"
  proxyUrl?: string;
  customUserAgent?: string;
  includeSubtitles?: boolean;
  maxPlaylistItems?: number;
  socketTimeout?: number;
  userDataDir?: string;
}

export interface BaseMediaExtractor {
  readonly platform: SupportedPlatform;
  readonly name: string;
  canHandle(url: string): boolean;
  extractInfo(url: string, options?: ExtractionOptions): Promise<MediaInfo>;
}

export interface MediaDownloadProgressEvent {
  jobId: string;
  url: string;
  stage: MediaDownloadStage;
  percent: number;
  speed?: string;
  eta?: string;
  downloadedBytes?: number;
  totalBytes?: number;
  outputPath?: string;
  error?: string;
}

export interface MediaDownloadJob {
  id: string;
  url: string;
  title: string;
  cleanFileName: string;
  quality: StandardQuality;
  container: TargetContainer;
  saveFolder: string;
  status: 'downloading' | 'paused' | 'completed' | 'error' | 'cancelled';
  stage: MediaDownloadStage | 'cancelled' | 'paused';
  percent: number;
  speed: string;
  eta: string;
  downloadedBytes?: number;
  totalBytes?: number;
  outputPath?: string;
  error?: string;
  startTime: number;
  endTime?: number;
  tempFiles: Set<string>;
  abortController?: AbortController;
  mediaInfo?: MediaInfo;
  options?: any;
}
