import {
  BaseMediaExtractor,
  ExtractionOptions,
  MediaChapter,
  MediaFormatOption,
  MediaInfo,
  MediaSubtitleOption,
} from './types';
import { isYouTubeUrl } from './urlDetector';
import { binManager } from './bin/binManager';

/**
 * Sanitizes titles for NTFS / FAT32 Windows filesystem restrictions.
 */
export function sanitizeWindowsFilename(title: string): string {
  if (!title) return 'youtube_video';
  // Remove Windows invalid filename chars: < > : " / \ | ? *
  let sanitized = title.replace(/[<>:"/\\|?*]/g, '').trim();
  // Strip control characters
  sanitized = sanitized.replace(/[\x00-\x1f\x80-\x9f]/g, '');
  // Prevent Windows reserved filenames (CON, PRN, AUX, NUL, COM1-9, LPT1-9)
  if (/^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(\..*)?$/i.test(sanitized)) {
    sanitized = `_${sanitized}`;
  }
  // Trim trailing periods and spaces (Windows restriction)
  sanitized = sanitized.replace(/[. ]+$/, '');
  return sanitized.slice(0, 200) || 'youtube_video';
}

function formatDurationSeconds(seconds?: number): string {
  if (!seconds || seconds <= 0) return '0:00';
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);

  if (hrs > 0) {
    return `${hrs}:${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  }
  return `${mins}:${secs.toString().padStart(2, '0')}`;
}

export class YouTubeExtractor implements BaseMediaExtractor {
  readonly platform = 'youtube' as const;
  readonly name = 'YouTube (yt-dlp core)';

  canHandle(url: string): boolean {
    return isYouTubeUrl(url);
  }

  /**
   * Transforms raw yt-dlp JSON dump into normalized YAS MediaInfo.
   */
  public parseYtdlpDump(json: Record<string, any>, originalUrl: string): MediaInfo {
    const title = json.title || 'Untitled Video';
    const cleanFileName = sanitizeWindowsFilename(title);
    const duration = typeof json.duration === 'number' ? json.duration : 0;

    const availableFormats: MediaFormatOption[] = [];
    const rawFormats = Array.isArray(json.formats) ? json.formats : [];

    for (const fmt of rawFormats) {
      const hasVideo = !!fmt.vcodec && fmt.vcodec !== 'none';
      const hasAudio = !!fmt.acodec && fmt.acodec !== 'none';

      if (!hasVideo && !hasAudio) continue;

      let resolution = fmt.resolution;
      if (!resolution && fmt.width && fmt.height) {
        resolution = `${fmt.width}x${fmt.height}`;
      } else if (!resolution && hasAudio && !hasVideo) {
        resolution = 'Audio only';
      }

      let qualityLabel = fmt.format_note || resolution || fmt.format_id;
      if (fmt.fps && fmt.fps > 30 && hasVideo) {
        qualityLabel = `${fmt.height}p${fmt.fps}`;
      }

      const isDashStream = hasVideo && !hasAudio; // Adaptive stream needing audio pairing

      availableFormats.push({
        formatId: String(fmt.format_id),
        ext: fmt.ext || 'mp4',
        resolution,
        width: fmt.width,
        height: fmt.height,
        fps: fmt.fps,
        vcodec: fmt.vcodec !== 'none' ? fmt.vcodec : undefined,
        acodec: fmt.acodec !== 'none' ? fmt.acodec : undefined,
        filesize: fmt.filesize || undefined,
        filesizeApprox: fmt.filesize_approx || undefined,
        tbr: fmt.tbr || undefined,
        vbr: fmt.vbr || undefined,
        abr: fmt.abr || undefined,
        qualityLabel,
        hasVideo,
        hasAudio,
        isDashStream,
        url: fmt.url,
        protocol: fmt.protocol,
        httpHeaders: fmt.http_headers,
      });
    }

    // Subtitles parsing
    const subtitles: MediaSubtitleOption[] = [];
    if (json.subtitles && typeof json.subtitles === 'object') {
      for (const [lang, subList] of Object.entries(json.subtitles)) {
        if (Array.isArray(subList) && subList.length > 0) {
          const firstSub = subList[0];
          subtitles.push({
            lang,
            name: firstSub.name || lang,
            ext: firstSub.ext || 'vtt',
            url: firstSub.url,
            isAutoGenerated: false,
          });
        }
      }
    }

    // Auto-captions parsing
    if (json.automatic_captions && typeof json.automatic_captions === 'object') {
      for (const [lang, subList] of Object.entries(json.automatic_captions)) {
        if (Array.isArray(subList) && subList.length > 0) {
          const firstSub = subList[0];
          subtitles.push({
            lang: `${lang}-auto`,
            name: `${firstSub.name || lang} (Auto)`,
            ext: firstSub.ext || 'vtt',
            url: firstSub.url,
            isAutoGenerated: true,
          });
        }
      }
    }

    // Chapters parsing
    const chapters: MediaChapter[] = [];
    if (Array.isArray(json.chapters)) {
      for (const chap of json.chapters) {
        chapters.push({
          title: chap.title || 'Chapter',
          startTime: chap.start_time || 0,
          endTime: chap.end_time || 0,
        });
      }
    }

    return {
      id: String(json.id || ''),
      originalUrl,
      platform: 'youtube',
      mediaType: json._type === 'playlist' ? 'playlist' : 'video',
      title,
      cleanFileName,
      description: json.description,
      uploader: json.uploader || json.channel,
      uploaderUrl: json.uploader_url || json.channel_url,
      duration,
      formattedDuration: formatDurationSeconds(duration),
      thumbnail: json.thumbnail || (Array.isArray(json.thumbnails) && json.thumbnails.length > 0 ? json.thumbnails[json.thumbnails.length - 1].url : undefined),
      availableFormats,
      subtitles: subtitles.length > 0 ? subtitles : undefined,
      chapters: chapters.length > 0 ? chapters : undefined,
      extractorName: this.name,
      extractedAt: Date.now(),
      rawMetadata: json,
    };
  }

  /**
   * Prepares execution arguments for yt-dlp child process.
   */
  public buildYtdlpArgs(url: string, options?: ExtractionOptions): string[] {
    const args = [
      '--dump-single-json',
      '--no-warnings',
      '--no-check-certificates',
      '--prefer-free-formats',
      '--socket-timeout', '10',
      '--no-write-subs',
      '--no-write-auto-subs',
      '--no-write-comments',
      '--no-write-thumbnail',
      '--remote-components', 'ejs:github',
    ];

    const jsRuntime = binManager.getJsRuntime();
    if (jsRuntime.path) {
      args.push('--js-runtimes', `${jsRuntime.runtime}:${jsRuntime.path}`);
    } else {
      args.push('--js-runtimes', jsRuntime.runtime);
    }
    args.push('--extractor-args', 'youtube:player_client=web,web_embedded;skip=translated_subs');

    if (options?.cookiesPath) {
      const pathModule = require('path');
      const resolved = pathModule.isAbsolute(options.cookiesPath)
        ? options.cookiesPath
        : pathModule.resolve(options.cookiesPath);
      args.push('--cookies', resolved);
    } else if (options?.browserCookies) {
      args.push('--cookies-from-browser', options.browserCookies);
    }

    if (options?.proxyUrl) {
      args.push('--proxy', options.proxyUrl);
    }

    if (options?.customUserAgent) {
      args.push('--user-agent', options.customUserAgent);
    }

    if (options?.maxPlaylistItems && options.maxPlaylistItems > 0) {
      args.push('--playlist-end', String(options.maxPlaylistItems));
    } else {
      args.push('--no-playlist');
    }

    args.push(url);
    return args;
  }

  /**
   * Extracts media metadata using yt-dlp child process.
   */
  async extractInfo(url: string, options?: ExtractionOptions): Promise<MediaInfo> {
    if (!this.canHandle(url)) {
      throw new Error(`YouTubeExtractor cannot handle URL: ${url}`);
    }

    const args = this.buildYtdlpArgs(url, options);

    try {
      const result = await binManager.executeYtdlp(args, {
        timeoutMs: 45000,
      });

      if (!result.stdout || !result.stdout.trim()) {
        throw new Error('yt-dlp returned an empty response for this URL.');
      }

      let parsedJson: Record<string, any>;
      try {
        parsedJson = JSON.parse(result.stdout.trim());
      } catch (jsonErr: any) {
        throw new Error(`Failed to parse yt-dlp metadata JSON: ${jsonErr.message}`);
      }

      return this.parseYtdlpDump(parsedJson, url);
    } catch (error: any) {
      // Re-throw with formatted context for UI handling
      const message = error.message || 'Unknown error occurred during YouTube extraction.';
      const enrichedError: any = new Error(message);
      enrichedError.platform = this.platform;
      enrichedError.originalUrl = url;
      enrichedError.rawError = error;
      throw enrichedError;
    }
  }
}
