import fs from 'fs';
import path from 'path';
import os from 'os';

export interface CookieItem {
  domain: string;
  name: string;
  value: string;
  path?: string;
  secure?: boolean;
  httpOnly?: boolean;
  expirationDate?: number; // timestamp in seconds
}

export class NetscapeCookieExporter {
  /**
   * Converts a list of standard cookie objects into Netscape cookie file format string.
   */
  public static formatNetscape(cookies: CookieItem[]): string {
    const lines = [
      '# Netscape HTTP Cookie File',
      '# https://curl.se/docs/http-cookies.html',
      '# Generated by YAS Downloader Session Manager',
      '',
    ];

    for (const c of cookies) {
      if (!c.domain || !c.name) continue;

      let domain = c.domain;
      const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
      const cookiePath = c.path || '/';
      const secure = c.secure ? 'TRUE' : 'FALSE';
      const expires = c.expirationDate ? Math.floor(c.expirationDate) : Math.floor(Date.now() / 1000) + 86400 * 365;
      const name = c.name;
      const value = c.value || '';

      lines.push(`${domain}\t${includeSubdomains}\t${cookiePath}\t${secure}\t${expires}\t${name}\t${value}`);
    }

    return lines.join('\n');
  }

  /**
   * Writes cookies to a temporary Netscape cookies file.
   */
  public static exportToTempFile(cookies: CookieItem[], prefix: string = 'yas_cookies'): string {
    const tmpDir = os.tmpdir();
    const filePath = path.join(tmpDir, `${prefix}_${Date.now()}_${Math.random().toString(36).substring(2, 8)}.txt`);
    const content = this.formatNetscape(cookies);
    fs.writeFileSync(filePath, content, 'utf8');
    return filePath;
  }

  /**
   * Auto-detects custom cookies.txt in common user directories.
   */
  public static findCustomCookiesFile(): string | undefined {
    const homeDir = os.homedir();
    const candidates = [
      path.join(homeDir, 'cookies.txt'),
      path.join(homeDir, 'Downloads', 'cookies.txt'),
      path.join(homeDir, 'Desktop', 'cookies.txt'),
      path.join(process.cwd(), 'cookies.txt'),
    ];

    if (process.env.LOCALAPPDATA) {
      candidates.push(path.join(process.env.LOCALAPPDATA, 'YAS-Downloader', 'cookies.txt'));
    }

    for (const p of candidates) {
      try {
        if (fs.existsSync(p) && fs.statSync(p).isFile() && fs.statSync(p).size > 10) {
          return p;
        }
      } catch {}
    }

    return undefined;
  }
}
